### ISSUE TITLE
Using stable alpine version

### ISSUE THREAD

**Issue by jakubknejzlik** [xueshanf/docker-awscli#6]
Hello 👋  ... Is it possible to use stable version of alpine in your Dockerfile? I've hit some bumps trying to add docker during build and `alpine:edge` seems to be the problem (currently `ERROR: iptables-1.6.2-r0: BAD signature` , works fine on alpine:3.5).

**Comment by xueshanf** [comment]
@jakubknejzlik do you think you can try again? looks like last night's alpine edge build has iptables-1.6.2-r2...

**Comment by jakubknejzlik** [comment]
Hi @xueshanf, the question was more about “do you need to use edge”? Even the owner don’t recommend using it for production.

**Comment by xueshanf** [comment]
Hi @jakubknejzlik, ah I see. No need to use edge.

**Comment by xueshanf** [comment]
@jakubknejzlik The base image is back to stable 3.9. It's better to be a little conservative as a base image :). Hopefully your problem will be addressed!

**Comment by xueshanf** [comment]
Reverted to stable image.
