### ISSUE TITLE
Update to latest awscli

### ISSUE THREAD

**Issue by monemihir** [xueshanf/docker-awscli#8]
Hi,

Any chance you can release an updated version of the container?

The current awscli version is 1.16 in the container but the latest released by AWS is 1.18. 

We need to use some commands from latest version.

**Comment by xueshanf** [comment]
@monemihir Upgraded to alline-3.11 base image and AWS CLI to 1.18.22.
```
docker run --rm  xueshanf/awscli aws --version 
aws-cli/1.18.22 Python/2.7.16 Linux/4.19.76-linuxkit botocore/1.15.22
```
Thanks!
