### ISSUE TITLE
Require docker images for ARM64

### ISSUE THREAD

**Issue by odidev** [xueshanf/docker-awscli#9]
Hi Team,

I am trying to use the docker image of this package in the ARM64 platform. As it is unavailable, I have successfully built the [same ](https://hub.docker.com/layers/odidev/awscli/latest/images/sha256-17e39c6210c6026a5e2b2314618c5cf11dcc2e28cf3c5e3a73c77dde8a3868d4?context=repo
)for ARM64 platform.

ARM64 docker image: https://hub.docker.com/layers/odidev/awscli/latest/images/sha256-17e39c6210c6026a5e2b2314618c5cf11dcc2e28cf3c5e3a73c77dde8a3868d4?context=repo

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on Docker hub?

**Comment by pmer** [comment]
Thank you for sharing this image on Docker Hub, it's great!

Just ran into the same problem.

AMD64 images work on the Apple M1 chip because it can run them via Rosetta 2, however they do not work on the AWS Graviton chips, which means it cannot be used on AWS ARM instances.

**Comment by xueshanf** [comment]
@odidev I will look into arm64 image build. As for how to auto build and publish image to docker hub, one way is to use docket hub’s auto build feature: https://docs.docker.com/docker-hub/builds/. That how this repo’s image is built and published. Of course you can run your build elsewhere and use your docker credential to publish image.

**Comment by xueshanf** [comment]
@odidev @pmer Now the cicd job will build multi-platform and push to github. Many thanks to @odidev
